### ISSUE TITLE
Enchancement: Widgets functions

### ISSUE THREAD

**Issue by mnuel1** [finnsatoshi03/ProductivityApp#102]
sort by date
sort by recent
sort by stars
link starred events
add star events parameter in evenets
working searchbar

in conversation view: can input and send messages, if read the unread messaged will be labeled or looked as read

functionality. badge in calendars. when day selected show events for that day. add events labels date above. minimize calendar container

**Comment by finnsatoshi03** [comment]
Sort by Recent /
Working Searchbar /
Conversation View /
Calendar /

**Comment by finnsatoshi03** [comment]
Sort by Date /
